---
#
# Last Update:
# Wolfgang Hotwagner updated this file on 23. April 2024
#

# Disabling for Amazon Linux 2 as selinux is disabled by default.
- name: Disable the selinux
  ansible.posix.selinux:
    state: disabled
  when: (ansible_distribution != "Ubuntu") and (ansible_distribution != "Amazon")

- name: Tune the system settings
  ansible.builtin.import_tasks: tune.yml

- name: Include opensearch installation
  ansible.builtin.import_tasks: opensearch.yml

- name: Include security plugin for opensearch
  ansible.builtin.import_tasks: security.yml

# After the cluster forms successfully for the first time,
# remove the cluster.initial_master_nodes setting from each nodes' configuration.
- name: Remove `cluster.initial_master_nodes` setting from configuration
  ansible.builtin.command: sed -i '/cluster.initial_master_nodes/d' "{{ os_conf_dir }}/opensearch.yml"

- name: Include tests
  ansible.builtin.import_tasks: test.yml
  when: os_test is truthy
