---

- name: Set vm.max_map_count in sysctl.conf
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144

- name: Set open files limit in sysctl.conf
  ansible.posix.sysctl:
    name: fs.file-max
    value: 65536

- name: Include opensearch installation
  ansible.builtin.import_tasks: 
    file: 01_install.yml

- name: Include security plugin for opensearch
  ansible.builtin.import_tasks: 
    file: 02_security.yml

# After the cluster forms successfully for the first time, remove the
# cluster.initial_master_nodes setting from each nodes' configuration.

- name: Remove line containing 'cluster.initial_master_nodes' from opensearch.yml
  ansible.builtin.lineinfile:
    path: "{{ os_conf_dir }}/opensearch.yml"
    regexp: '^cluster\.initial_master_nodes'
    state: absent

- name: Make sure opensearch is started
  ansible.builtin.service:
    name: opensearch
    state: started
    enabled: true

- name: Include checks
  ansible.builtin.import_tasks: 
    file: 03_checks.yml